'use strict'

module.exports = [{
	meta: {tags: []},
	feature: [
	{
		geomtype: 0,
		geomserial: 0,
		geom: Buffer.from('01010000004c7d7cd3d2c253c064c2cf353a8b4540', 'hex'),
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		tags: [
			{key: 'name_fr', value: 'chutes du Niagara', type: 0},
			{key: 'name_hi', value: 'नायाग्रा जल प्रपात', type: 0},
			{key: 'name_it', value: 'cascate del Niagara', type: 0},
			{key: 'name_ko', value: '나이아가라 폭포', type: 0},
			{key: 'name_sv', value: 'Niagarafallen', type: 0},
			{key: 'featurecla', value: 'waterfall', type: 0},
			{key: 'name_es', value: 'Cataratas del Niágara', type: 0},
			{key: 'name_pt', value: 'Cataratas do Niágara', type: 0},
			{key: 'scalerank', value: 2, type: 2},
			{key: 'name_de', value: 'Niagarafälle', type: 0},
			{key: 'ne_id', value: 1159105019, type: 2},
			{key: 'name_ar', value: 'شلالات نياجارا', type: 0},
			{key: 'name_en', value: 'Niagara Falls', type: 0},
			{key: 'name_hu', value: 'Niagara-vízesés', type: 0},
			{key: 'name_pl', value: 'Wodospad Niagara', type: 0},
			{key: 'name_tr', value: 'Niagara Şelalesi', type: 0},
			{key: 'name_vi', value: 'Thác Niagara', type: 0},
			{key: 'name_bn', value: 'নায়াগ্রা জলপ্রপাত', type: 0},
			{key: 'name_ja', value: 'ナイアガラの滝', type: 0},
			{key: 'name_zh', value: '尼亚加拉瀑布', type: 0},
			{key: 'name_alt', value: null, type: 0},
			{key: 'lat_y', value: 43.087653, type: 2},
			{key: 'subregion', value: null, type: 0},
			{key: 'name_ru', value: 'Ниагарский водопад', type: 0},
			{key: 'name_nl', value: 'Niagarawatervallen', type: 0},
			{key: 'wikidataid', value: 'Q34221', type: 0},
			{key: 'name', value: 'Niagara Falls', type: 0},
			{key: 'long_x', value: -79.044073, type: 2},
			{key: 'region', value: 'North America', type: 0},
			{key: 'min_zoom', value: 5, type: 2},
			{key: 'label', value: 'Niagara Falls', type: 0},
			{key: 'name_el', value: 'Καταρράκτες του Νιαγάρα', type: 0},
			{key: 'wdid_score', value: 3, type: 2},
			{key: 'comment', value: null, type: 0},
			{key: 'name_id', value: 'Niagara', type: 0}
		]
	}, {
		geomtype: 0,
		geomserial: 0,
		geom: Buffer.from('010100000098faf8a6e9074fc020137eae61bf1640', 'hex'),
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		tags: [
			{key: 'comment', value: null, type: 0},
			{key: 'name_id', value: 'Air terjun Angel', type: 0},
			{key: 'name_pt', value: 'Salto Ángel', type: 0},
			{key: 'name_vi', value: 'Thác nước Ángel', type: 0},
			{key: 'name_el', value: 'Καταρράκτες Έιντζελ', type: 0},
			{key: 'name_alt', value: 'Angel Falls', type: 0},
			{key: 'region', value: 'South America', type: 0},
			{key: 'label', value: 'Salto Angel', type: 0},
			{key: 'name_en', value: 'Angel Falls', type: 0},
			{key: 'scalerank', value: 2, type: 2},
			{key: 'name_nl', value: 'Ángelwaterval', type: 0},
			{key: 'name_ru', value: 'Анхель', type: 0},
			{key: 'name_zh', value: '安赫尔瀑布', type: 0},
			{key: 'wdid_score', value: 5, type: 2},
			{key: 'lat_y', value: 5.686836, type: 2},
			{key: 'subregion', value: null, type: 0},
			{key: 'name_hi', value: 'एन्जिल जलप्रपात', type: 0},
			{key: 'name_pl', value: 'Salto Angel', type: 0},
			{key: 'name_tr', value: 'Angel Şelalesi', type: 0},
			{key: 'name_ar', value: 'شلالات آنجل', type: 0},
			{key: 'name_fr', value: 'Salto Angel', type: 0},
			{key: 'name_hu', value: 'Angel-vízesés', type: 0},
			{key: 'name_it', value: 'Salto Angel', type: 0},
			{key: 'featurecla', value: 'waterfall', type: 0},
			{key: 'name', value: 'Salto Angel', type: 0},
			{key: 'long_x', value: -62.061848, type: 2},
			{key: 'min_zoom', value: 5, type: 2},
			{key: 'name_ko', value: '앙헬 폭포', type: 0},
			{key: 'name_de', value: 'Salto Ángel', type: 0},
			{key: 'name_es', value: 'Salto Ángel', type: 0},
			{key: 'name_sv', value: 'Angelfallen', type: 0},
			{key: 'wikidataid', value: 'Q80299', type: 0},
			{key: 'name_bn', value: 'অ্যাঞ্জেল জলপ্রপাত', type: 0},
			{key: 'name_ja', value: 'エンジェルフォール', type: 0},
			{key: 'ne_id', value: 1159105051, type: 2}
		]
	}, {
		geomtype: 0,
		geomserial: 0,
		geom: Buffer.from('010100000098faf8a69f4a4bc0387b60947b9139c0', 'hex'),
		left: 0,
		right: 0,
		top: 0,
		bottom: 0,
		tags: [
			{key: 'label', value: 'Iguazu Falls', type: 0},
			{key: 'name_ar', value: 'شلالات إجوازو', type: 0},
			{key: 'name_fr', value: "chutes d'Iguazú", type: 0},
			{key: 'name_it', value: "cascate dell'Iguazú", type: 0},
			{key: 'name_ja', value: 'イグアスの滝', type: 0},
			{key: 'name_vi', value: 'Thác Iguazu', type: 0},
			{key: 'wdid_score', value: 5, type: 2},
			{key: 'scalerank', value: 2, type: 2},
			{key: 'long_x', value: -54.582842, type: 2},
			{key: 'subregion', value: null, type: 0},
			{key: 'name_bn', value: 'ইগুয়াসু জলপ্রপাত', type: 0},
			{key: 'name_pl', value: 'Wodospad Iguazú', type: 0},
			{key: 'name_ru', value: 'Игуасу', type: 0},
			{key: 'name_el', value: 'Καταρράκτες Ιγκουασού', type: 0},
			{key: 'name_hu', value: 'Iguazú-vízesés', type: 0},
			{key: 'name_id', value: 'Air terjun Iguazu', type: 0},
			{key: 'name_tr', value: 'Iguazú Şelalesi', type: 0},
			{key: 'wikidataid', value: 'Q36332', type: 0},
			{key: 'name_ko', value: '이구아수 폭포', type: 0},
			{key: 'name_nl', value: 'Watervallen van de Iguaçu', type: 0},
			{key: 'name_sv', value: 'Iguazúfallen', type: 0},
			{key: 'name_zh', value: '伊瓜苏瀑布', type: 0},
			{key: 'name', value: 'Iguazu Falls', type: 0},
			{key: 'comment', value: null, type: 0},
			{key: 'name_es', value: 'Cataratas del Iguazú', type: 0},
			{key: 'featurecla', value: 'waterfall', type: 0},
			{key: 'name_alt', value: null, type: 0},
			{key: 'region', value: 'South America', type: 0},
			{key: 'min_zoom', value: 5, type: 2},
			{key: 'name_pt', value: 'Cataratas do Iguaçu', type: 0},
			{key: 'lat_y', value: -25.568265, type: 2},
			{key: 'name_en', value: 'Iguaçu Falls', type: 0},
			{key: 'name_de', value: 'Iguazú-Wasserfälle', type: 0},
			{key: 'name_hi', value: null, type: 0},
			{key: 'ne_id', value: 1159105053, type: 2}
		]
	}]
}]
